#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# Infra_install.sh — AZUL Infrastructure Install Script
# ═══════════════════════════════════════════════════════════════════════════════
#
# Installs the AZUL infrastructure layer: Kafka, OpenSearch, MinIO, Keycloak,
# Postgres, and all supporting certificates. Idempotent — safe to re-run.
#
# Usage:
#   ./Infra_install.sh           # Full install (all steps)
#   ./Infra_install.sh --step N  # Run from step N onwards
#   ./Infra_install.sh --check   # Just verify current state
#   ./Infra_install.sh --creds   # Just generate credentials file
#
# ═══════════════════════════════════════════════════════════════════════════════
#
# FILES REQUIRED (all relative to /data/AZUL/)
# ─────────────────────────────────────────────────────────────────────────────
#
# HELM CHARTS:
#   azul-app/infra/                                          Infrastructure chart (pre-patched)
#   charts/strimzi-kafka-operator-helm-3-chart-0.50.0.tgz   Strimzi Kafka operator
#   charts/opensearch-operator-2.8.0.tgz                     OpenSearch operator
#
# VALUES FILES:
#   azul-infra-values.yaml               Overrides for infra chart
#
# SCRIPTS (used by this installer):
#   scripts/setup-certs.sh               Certificate management functions (sourced)
#   setup-keycloak.sh                    Keycloak realm/client/user setup
#
# GENERATED BY THIS SCRIPT:
#   .azul-credentials                    Static passwords (created once, reused)
#
# ═══════════════════════════════════════════════════════════════════════════════
#
# CONTAINER IMAGES — FULL LIST
# ─────────────────────────────────────────────────────────────────────────────
#
# To change registries for offline/air-gapped install, edit these locations:
#
# ┌────┬─────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────┐
# │ #  │ Image                                                   │ File & Location to Change                                    │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │  1 │ minio/minio:RELEASE.2025-09-07T16-13-09Z               │ azul-infra-values.yaml → minio.main.image       (line 22)    │
# │  2 │ quay.io/keycloak/keycloak:26.1                         │ azul-infra-values.yaml → keycloak.image          (line 641)   │
# │  3 │ postgres:17.4                                          │ azul-app/infra/templates/keycloak/postgres.yaml  (line 46)    │
# │  4 │ deviceinsight/kafkactl:v5.13.0-ubuntu                  │ azul-infra-values.yaml → kafka.kafkactl.image    (line 607)   │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │    │ OPERATOR-MANAGED (pulled by operator, version in values)│                                                              │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │  5 │ docker.io/opensearchproject/opensearch:3.2.0           │ Version from: azul-infra-values.yaml line 94                  │
# │    │                                                         │ Registry: opensearch-operator default                         │
# │  6 │ docker.io/opensearchproject/opensearch-dashboards:3.2.0│ Version from: azul-infra-values.yaml line 133                 │
# │    │                                                         │ Registry: opensearch-operator default                         │
# │  7 │ quay.io/strimzi/kafka:0.50.0-kafka-4.0.0              │ Version from: azul-infra-values.yaml line 589                 │
# │    │                                                         │ Registry: strimzi-operator default                            │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │    │ OPERATOR IMAGES (from .tgz charts, override with --set)│                                                              │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │  8 │ quay.io/strimzi/operator:0.50.0                        │ charts/strimzi...tgz → --set image.registry, image.repository │
# │  9 │ opensearchproject/opensearch-operator:2.8.0             │ charts/opensearch...tgz → --set manager.image.*               │
# │ 10 │ gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0             │ charts/opensearch...tgz → --set kubeRbacProxy.image.*         │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │    │ INIT CONTAINERS (auto-created by opensearch-operator)  │                                                              │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │ 11 │ docker.io/busybox:latest                               │ opensearch-operator default (init containers for sysctl)      │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │    │ STRIMZI EXTRA (pulled automatically by operator)       │                                                              │
# ├────┼─────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────┤
# │ 12 │ quay.io/strimzi/operator:0.50.0                        │ Entity operator (topic + user) — same as #8                   │
# │ 13 │ quay.io/strimzi/kafka:0.50.0-kafka-4.1.1              │ Kafka exporter — auto-selected by Strimzi                     │
# └────┴─────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────────────┘
#
# ═══════════════════════════════════════════════════════════════════════════════
#
# INSTALL STEPS (10 total)
# ─────────────────────────────────────────────────────────────────────────────
#  1. Generate credentials          (.azul-credentials)
#  2. Install Strimzi operator      (kafka namespace)
#  3. Install OpenSearch operator   (opensearch-operator namespace)
#  4. Create namespace + secrets    (azul-infra namespace)
#  5. Helm install azul-infra       (Kafka, OpenSearch, MinIO, Keycloak, Postgres)
#  6. Patch CA + wait for pods      (cert-manager CA → chart bundle, wait for ready)
#  7. OpenSearch unsafe-bootstrap   (required for single-node cluster)
#  8. CoreDNS + Keycloak TLS cert   (DNS resolution + TLS certificate)
#  9. Bake CA into OpenSearch       (helm upgrade + restart for OIDC trust)
# 10. Keycloak setup + verify       (realm, clients, users, health checks)
#
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

# Source central config
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AZUL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${AZUL_DIR}/azul.conf"
FILESERVER="${SERVICE_IP}:${FILESERVER_PORT}"
REGISTRY="${SERVICE_IP}:${REGISTRY_PORT}"

# ── Paths ──────────────────────────────────────────────────────────────────
INFRA_CHART="${AZUL_DIR}/azul-app/infra"
INFRA_VALUES="${AZUL_DIR}/azul-infra-values.yaml"
CREDS_FILE="${AZUL_DIR}/.azul-credentials"
CERTS_SCRIPT="${AZUL_DIR}/scripts/setup-certs.sh"
KEYCLOAK_SCRIPT="${AZUL_DIR}/scripts/setup-keycloak.sh"

STRIMZI_CHART="${AZUL_DIR}/charts/strimzi-kafka-operator-helm-3-chart-0.50.0.tgz"
OPENSEARCH_CHART="${AZUL_DIR}/charts/opensearch-operator-2.8.0.tgz"

# OpenSearch image used for unsafe-bootstrap Job (must match opensearch.general.version)
OPENSEARCH_IMAGE="docker.io/opensearchproject/opensearch:3.2.0"

DISCORD_WEBHOOK="${DISCORD_WEBHOOK:-}"  # Set via environment or .azul-credentials

# ── Helpers ────────────────────────────────────────────────────────────────
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
die() { log "FATAL: $*"; exit 1; }

send_discord() {
    local operation="$1" status="$2" details="${3:-}" color
    [ "$status" = "success" ] && color="65280" || color="16711680"
    curl -sf -H "Content-Type: application/json" -d "{
        \"embeds\": [{
            \"title\": \"Azul Infra Install\",
            \"color\": $color,
            \"fields\": [
                {\"name\": \"Operation\", \"value\": \"$operation\", \"inline\": true},
                {\"name\": \"Status\", \"value\": \"$status\", \"inline\": true},
                {\"name\": \"Date\", \"value\": \"$(date '+%Y-%m-%d %H:%M:%S')\", \"inline\": false},
                {\"name\": \"Details\", \"value\": \"${details:-N/A}\", \"inline\": false}
            ]
        }]
    }" "$DISCORD_WEBHOOK" >/dev/null 2>&1 || true
}

# ═══════════════════════════════════════════════════════════════════════════════
# PREFLIGHT — verify all required files exist
# ═══════════════════════════════════════════════════════════════════════════════
preflight() {
    log "=== Preflight Checks ==="
    local ok=true

    for f in "$INFRA_CHART/Chart.yaml" "$INFRA_VALUES" "$STRIMZI_CHART" \
             "$OPENSEARCH_CHART" "$CERTS_SCRIPT" "$KEYCLOAK_SCRIPT"; do
        if [ ! -e "$f" ]; then
            log "MISSING: $f"
            ok=false
        else
            log "  OK: $f"
        fi
    done

    # Check tools
    for cmd in kubectl helm python3 openssl curl; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            log "MISSING command: $cmd"
            ok=false
        fi
    done

    # Check cluster access
    if ! kubectl cluster-info >/dev/null 2>&1; then
        log "ERROR: Cannot reach Kubernetes cluster (check KUBECONFIG=$KUBECONFIG)"
        ok=false
    fi

    # Check cert-manager
    if ! kubectl get crd certificates.cert-manager.io >/dev/null 2>&1; then
        log "ERROR: cert-manager not installed (required for TLS certificates)"
        ok=false
    fi

    if [ "$ok" = false ]; then
        die "Preflight checks failed — fix the above before continuing"
    fi
    log "All preflight checks passed"
    log ""
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1: Generate credentials
# ═══════════════════════════════════════════════════════════════════════════════
step1_credentials() {
    log "============================================"
    log "=== STEP 1: Generate Credentials ==="
    log "============================================"

    # Check if credentials already have static (non-$()) values
    if [ -f "$CREDS_FILE" ]; then
        if grep -q '$(openssl' "$CREDS_FILE" 2>/dev/null; then
            log "WARNING: $CREDS_FILE contains dynamic \$(openssl ...) values"
            log "Regenerating with static values..."
        else
            log "Credentials file exists with static values: $CREDS_FILE"
            return 0
        fi
    fi

    log "Generating new credentials → $CREDS_FILE"
    cat > "$CREDS_FILE" <<EOF
# AZUL Infrastructure Credentials — SENSITIVE — DO NOT COMMIT
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# These are STATIC values. Do not change after secrets are created in cluster.

## MinIO (Main S3 storage)
S3_ACCESS_KEY=$(openssl rand -hex 16)
S3_SECRET_KEY=$(openssl rand -hex 32)

## OpenSearch Admin
OS_ADMIN_USER=admin
OS_ADMIN_PASS=$(openssl rand -base64 24)

## OpenSearch Dashboard (kibanaserver)
OS_DASH_USER=kibanaserver
OS_DASH_PASS=$(openssl rand -base64 24)

## Keycloak
KC_DB_PASSWORD=$(openssl rand -base64 24)
KC_ADMIN_USER=admin
KC_ADMIN_PASSWORD=$(openssl rand -base64 24)
EOF
    chmod 600 "$CREDS_FILE"
    log "Credentials saved (static values, safe to re-source)"
    log "  File: $CREDS_FILE"
}

# Load credentials from file (key=value, ignoring comments and blanks)
load_creds() {
    if [ ! -f "$CREDS_FILE" ]; then
        die "Credentials file not found: $CREDS_FILE — run step 1 first"
    fi
    if grep -q '$(openssl' "$CREDS_FILE" 2>/dev/null; then
        die "Credentials file has dynamic values — run step 1 to regenerate"
    fi
    while IFS='=' read -r key value; do
        case "$key" in
            S3_ACCESS_KEY)    S3_ACCESS_KEY="$value" ;;
            S3_SECRET_KEY)    S3_SECRET_KEY="$value" ;;
            OS_ADMIN_PASS)    OS_ADMIN_PASS="$value" ;;
            OS_DASH_PASS)     OS_DASH_PASS="$value" ;;
            KC_DB_PASSWORD)   KC_DB_PASSWORD="$value" ;;
            KC_ADMIN_PASSWORD) KC_ADMIN_PASSWORD="$value" ;;
        esac
    done < <(grep -v '^#' "$CREDS_FILE" | grep -v '^\s*$' | grep '=')
    log "Credentials loaded from $CREDS_FILE"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2: Install Strimzi Kafka Operator
# ═══════════════════════════════════════════════════════════════════════════════
step2_strimzi() {
    log ""
    log "============================================"
    log "=== STEP 2: Install Strimzi Operator ==="
    log "============================================"
    log "Chart: $STRIMZI_CHART"
    log "Namespace: kafka"
    log "Image: quay.io/strimzi/operator:0.50.0"

    if helm status strimzi-kafka-operator -n kafka >/dev/null 2>&1; then
        log "Strimzi already installed, skipping"
    else
        helm install strimzi-kafka-operator "$STRIMZI_CHART" \
            --namespace kafka --create-namespace \
            --set watchAnyNamespace=true \
            --timeout 3m
        log "Strimzi operator installed"
    fi

    log "Waiting for Strimzi operator pod..."
    kubectl wait --for=condition=ready pod -l name=strimzi-cluster-operator \
        -n kafka --timeout=120s
    log "Strimzi operator: READY"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3: Install OpenSearch Operator
# ═══════════════════════════════════════════════════════════════════════════════
step3_opensearch_operator() {
    log ""
    log "============================================"
    log "=== STEP 3: Install OpenSearch Operator ==="
    log "============================================"
    log "Chart: $OPENSEARCH_CHART"
    log "Namespace: opensearch-operator"
    log "Images: opensearchproject/opensearch-operator:2.8.0, gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0"

    if helm status opensearch-operator -n opensearch-operator >/dev/null 2>&1; then
        log "OpenSearch operator already installed, skipping"
    else
        helm install opensearch-operator "$OPENSEARCH_CHART" \
            --namespace opensearch-operator --create-namespace \
            --timeout 3m
        log "OpenSearch operator installed"
    fi

    log "Waiting for OpenSearch operator pod..."
    kubectl wait --for=condition=ready pod -l control-plane=controller-manager \
        -n opensearch-operator --timeout=120s
    log "OpenSearch operator: READY"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4: Create namespace and secrets
# ═══════════════════════════════════════════════════════════════════════════════
step4_namespace_secrets() {
    log ""
    log "============================================"
    log "=== STEP 4: Create Namespace + Secrets ==="
    log "============================================"

    load_creds

    # Create namespace
    kubectl create namespace azul-infra 2>/dev/null && log "Created namespace: azul-infra" \
        || log "Namespace azul-infra already exists"

    # Secret 1: s3-keys (MinIO)
    if ! kubectl get secret s3-keys -n azul-infra >/dev/null 2>&1; then
        kubectl create secret generic s3-keys -n azul-infra \
            --from-literal=accesskey="$S3_ACCESS_KEY" \
            --from-literal=secretkey="$S3_SECRET_KEY"
        log "Created secret: s3-keys (MinIO access)"
    else
        log "Secret s3-keys already exists"
    fi

    # Secret 2: azul-cluster-admincredentials (OpenSearch admin)
    if ! kubectl get secret azul-cluster-admincredentials -n azul-infra >/dev/null 2>&1; then
        kubectl create secret generic azul-cluster-admincredentials -n azul-infra \
            --from-literal=username=admin \
            --from-literal=password="$OS_ADMIN_PASS"
        log "Created secret: azul-cluster-admincredentials (OpenSearch admin)"
    else
        log "Secret azul-cluster-admincredentials already exists"
    fi

    # Secret 3: azul-cluster-dashboardcredentials (OpenSearch dashboards)
    if ! kubectl get secret azul-cluster-dashboardcredentials -n azul-infra >/dev/null 2>&1; then
        kubectl create secret generic azul-cluster-dashboardcredentials -n azul-infra \
            --from-literal=username=kibanaserver \
            --from-literal=password="$OS_DASH_PASS"
        log "Created secret: azul-cluster-dashboardcredentials (OpenSearch dashboards)"
    else
        log "Secret azul-cluster-dashboardcredentials already exists"
    fi

    # Secret 4: keycloak (Keycloak DB + admin password)
    if ! kubectl get secret keycloak -n azul-infra >/dev/null 2>&1; then
        kubectl create secret generic keycloak -n azul-infra \
            --from-literal=DB_PASSWORD="$KC_DB_PASSWORD" \
            --from-literal=KEYCLOAK_ADMIN_PASSWORD="$KC_ADMIN_PASSWORD"
        log "Created secret: keycloak (DB + admin)"
    else
        log "Secret keycloak already exists"
    fi

    log ""
    log "All secrets in azul-infra:"
    kubectl get secrets -n azul-infra --no-headers | while read -r line; do log "  $line"; done
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5: Helm install azul-infra
# ═══════════════════════════════════════════════════════════════════════════════
step5_helm_install() {
    log ""
    log "============================================"
    log "=== STEP 5: Helm Install azul-infra ==="
    log "============================================"
    log "Chart:  $INFRA_CHART"
    log "Values: $INFRA_VALUES"
    log ""
    log "Images that will be pulled by this chart:"
    log "  minio/minio:RELEASE.2025-09-07T16-13-09Z          ← azul-infra-values.yaml line 22"
    log "  quay.io/keycloak/keycloak:26.1                     ← azul-infra-values.yaml line 641"
    log "  postgres:17.4                                      ← azul-app/infra/templates/keycloak/postgres.yaml line 46"
    log "  deviceinsight/kafkactl:v5.13.0-ubuntu              ← azul-infra-values.yaml line 607"
    log "  docker.io/opensearchproject/opensearch:3.2.0       ← opensearch-operator (version: azul-infra-values.yaml line 94)"
    log "  docker.io/opensearchproject/opensearch-dashboards:3.2.0 ← opensearch-operator (version: line 133)"
    log "  quay.io/strimzi/kafka:0.50.0-kafka-4.0.0          ← strimzi-operator (version: azul-infra-values.yaml line 589)"
    log "  docker.io/busybox:latest                           ← opensearch-operator init containers"
    log ""

    if helm status azul-infra -n azul-infra >/dev/null 2>&1; then
        log "azul-infra already installed, running helm upgrade..."
        helm upgrade azul-infra "$INFRA_CHART" -n azul-infra -f "$INFRA_VALUES" --timeout 10m
    else
        helm install azul-infra "$INFRA_CHART" -n azul-infra -f "$INFRA_VALUES" --timeout 10m
    fi
    log "azul-infra chart deployed"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 6: Patch CA into chart + wait for pods
# ═══════════════════════════════════════════════════════════════════════════════
step6_ca_and_wait() {
    log ""
    log "============================================"
    log "=== STEP 6: Patch CA + Wait for Pods ==="
    log "============================================"

    # Source certificate functions
    source "$CERTS_SCRIPT"

    # Wait for cert-manager to create the CA secret
    log "Waiting for cert-manager CA certificate (azul-opensearch-ca-cert)..."
    wait_for_ca || die "CA certificate not created. Check cert-manager logs."
    log "CA certificate found"

    # Patch CA into chart's ca-certificates bundle file
    log "Patching CA into chart bundle: ${INFRA_CHART}/ca-certificates"
    patch_ca_into_chart

    # Wait for infrastructure pods
    log ""
    log "Waiting for infrastructure pods to be ready..."

    log "  Kafka (label: strimzi.io/component-type=kafka)..."
    kubectl wait --for=condition=ready pod \
        -l strimzi.io/component-type=kafka -n azul-infra --timeout=300s 2>/dev/null \
        && log "  Kafka: READY" || log "  WARNING: Kafka not ready within 300s"

    log "  MinIO (label: app=s3-store-minio)..."
    kubectl wait --for=condition=ready pod \
        -l app=s3-store-minio -n azul-infra --timeout=180s 2>/dev/null \
        && log "  MinIO: READY" || log "  WARNING: MinIO not ready within 180s"

    log "  Postgres (label: app=postgres)..."
    kubectl wait --for=condition=ready pod \
        -l app=postgres -n azul-infra --timeout=180s 2>/dev/null \
        && log "  Postgres: READY" || log "  WARNING: Postgres not ready within 180s"

    log "  Keycloak (label: app=keycloak)..."
    kubectl wait --for=condition=ready pod \
        -l app=keycloak -n azul-infra --timeout=300s 2>/dev/null \
        && log "  Keycloak: READY" || log "  WARNING: Keycloak not ready within 300s"

    log "  OpenSearch will be handled in step 7 (needs unsafe-bootstrap)"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 7: OpenSearch single-node unsafe-bootstrap
# ═══════════════════════════════════════════════════════════════════════════════
step7_opensearch_bootstrap() {
    log ""
    log "============================================"
    log "=== STEP 7: OpenSearch Unsafe-Bootstrap ==="
    log "============================================"
    log "Image for bootstrap job: $OPENSEARCH_IMAGE"
    log ""
    log "OpenSearch single-node requires 'unsafe-bootstrap' after every pod restart."
    log "This runs a Job that modifies the PVC data, then restarts the StatefulSet."

    # Check if OpenSearch is already ready
    local os_ready
    os_ready=$(kubectl get pod azul-opensearch-nodes-0 -n azul-infra \
        -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "Unknown")

    if [ "$os_ready" = "True" ]; then
        log "OpenSearch already Ready — skipping bootstrap"
        return 0
    fi

    log "OpenSearch not ready (status=$os_ready), running unsafe-bootstrap..."

    # Scale down operator so it doesn't fight us
    log "  Scaling down opensearch-operator..."
    kubectl scale deployment opensearch-operator-controller-manager \
        -n opensearch-operator --replicas=0 2>/dev/null || true
    sleep 5

    # Scale down OpenSearch StatefulSet
    log "  Scaling down azul-opensearch-nodes..."
    kubectl scale statefulset azul-opensearch-nodes -n azul-infra --replicas=0 2>/dev/null || true

    # Wait for pod to terminate
    log "  Waiting for OpenSearch pod to terminate..."
    local attempts=0
    while [ $attempts -lt 30 ]; do
        if ! kubectl get pod azul-opensearch-nodes-0 -n azul-infra >/dev/null 2>&1; then
            break
        fi
        sleep 5
        attempts=$((attempts + 1))
    done

    # Delete old bootstrap job if exists
    kubectl delete job opensearch-unsafe-bootstrap -n azul-infra 2>/dev/null || true

    # Create and run the unsafe-bootstrap Job
    log "  Running unsafe-bootstrap Job..."
    cat <<EOJOB | kubectl apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-unsafe-bootstrap
  namespace: azul-infra
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: bootstrap
        image: ${OPENSEARCH_IMAGE}
        command:
        - /bin/bash
        - -c
        - |
          echo "y" | /usr/share/opensearch/bin/opensearch-node unsafe-bootstrap
        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-azul-opensearch-nodes-0
EOJOB

    log "  Waiting for bootstrap Job to complete..."
    kubectl wait --for=condition=complete job/opensearch-unsafe-bootstrap \
        -n azul-infra --timeout=120s 2>/dev/null \
        && log "  Bootstrap Job: COMPLETED" \
        || log "  WARNING: Bootstrap Job may not have completed"

    # Clean up
    kubectl delete job opensearch-unsafe-bootstrap -n azul-infra 2>/dev/null || true

    # Scale back up
    log "  Scaling up azul-opensearch-nodes..."
    kubectl scale statefulset azul-opensearch-nodes -n azul-infra --replicas=1
    log "  Scaling up opensearch-operator..."
    kubectl scale deployment opensearch-operator-controller-manager \
        -n opensearch-operator --replicas=1 2>/dev/null || true

    # Wait for OpenSearch to come back
    log "  Waiting for OpenSearch pod to be Ready..."
    sleep 30
    kubectl wait --for=condition=ready pod/azul-opensearch-nodes-0 \
        -n azul-infra --timeout=180s 2>/dev/null \
        && log "  OpenSearch: READY" \
        || log "  WARNING: OpenSearch not ready within 180s"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 8: CoreDNS hosts + Keycloak TLS certificate
# ═══════════════════════════════════════════════════════════════════════════════
step8_coredns_and_keycloak_cert() {
    log ""
    log "============================================"
    log "=== STEP 8: CoreDNS + Keycloak TLS Cert ==="
    log "============================================"

    # Source certificate functions
    source "$CERTS_SCRIPT"

    # --- CoreDNS ---
    log "Checking CoreDNS for azul hosts entries..."
    local COREFILE
    COREFILE=$(kubectl get configmap coredns -n kube-system -o jsonpath='{.data.Corefile}' 2>/dev/null)

    if echo "$COREFILE" | grep -q "${KEYCLOAK_HOST}"; then
        log "CoreDNS already has azul hosts entries"
    else
        log "Adding azul hosts block to CoreDNS..."
        local HOSTS_BLOCK="    hosts {
        ${CLUSTER_IP} ${KEYCLOAK_HOST}
        ${CLUSTER_IP} ${OPENSEARCH_HOST}
        ${CLUSTER_IP} ${AZUL_HOST}
        fallthrough
    }"
        local NEW_COREFILE
        NEW_COREFILE=$(echo "$COREFILE" | HOSTS_BLOCK="$HOSTS_BLOCK" python3 -c "
import sys, os
content = sys.stdin.read()
hosts_block = os.environ['HOSTS_BLOCK']
lines = content.split('\n')
result = []
inserted = False
for line in lines:
    if 'forward' in line and not inserted:
        result.append(hosts_block.rstrip())
        inserted = True
    result.append(line)
if not inserted:
    result2 = []
    for line in reversed(result):
        if line.strip() == '}' and not inserted:
            result2.append(line)
            result2.append(hosts_block.rstrip())
            inserted = True
        else:
            result2.append(line)
    result = list(reversed(result2))
print('\n'.join(result), end='')
")
        kubectl create configmap coredns -n kube-system \
            --from-literal=Corefile="$NEW_COREFILE" \
            --dry-run=client -o yaml | kubectl apply -f -
        kubectl rollout restart deployment coredns -n kube-system
        log "CoreDNS updated with azul hosts"
        sleep 10
    fi

    # --- Keycloak TLS Certificate ---
    log ""
    log "Creating Keycloak TLS certificate (cert-manager)..."
    create_keycloak_cert
    log "Keycloak TLS cert: READY"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 9: Bake Test CA into OpenSearch cert bundle
# ═══════════════════════════════════════════════════════════════════════════════
step9_bake_ca() {
    log ""
    log "============================================"
    log "=== STEP 9: Bake CA into OpenSearch ==="
    log "============================================"
    log "This runs 'helm upgrade azul-infra' to push the patched ca-certificates"
    log "file into the opensearch-certs configmap, then restarts OpenSearch."
    log ""

    # Source certificate functions
    source "$CERTS_SCRIPT"

    # Check if already baked
    local has_test_ca
    has_test_ca=$(kubectl exec azul-opensearch-nodes-0 -n azul-infra -- \
        grep -c "Test CA" /usr/share/opensearch/config/certs/ca-certificates 2>/dev/null) || has_test_ca="0"

    if [ "$has_test_ca" -gt 0 ] 2>/dev/null; then
        log "Test CA already in OpenSearch cert bundle — skipping"
        return 0
    fi

    # Ensure chart bundle is patched
    patch_ca_into_chart

    # Helm upgrade to push patched bundle
    log "Running helm upgrade azul-infra..."
    helm upgrade azul-infra "$INFRA_CHART" -n azul-infra -f "$INFRA_VALUES" --timeout 5m
    log "Helm upgrade complete"

    # OpenSearch needs restart to pick up new configmap
    log "Restarting OpenSearch to pick up updated CA bundle..."
    log "(Single-node requires unsafe-bootstrap after restart)"

    # Re-run the bootstrap process
    step7_opensearch_bootstrap

    # Verify CA is now present
    has_test_ca=$(kubectl exec azul-opensearch-nodes-0 -n azul-infra -- \
        grep -c "Test CA" /usr/share/opensearch/config/certs/ca-certificates 2>/dev/null) || has_test_ca="0"
    if [ "$has_test_ca" -gt 0 ] 2>/dev/null; then
        log "Test CA confirmed in OpenSearch cert bundle"
    else
        log "WARNING: Test CA not found in OpenSearch — OIDC may not work"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 10: Keycloak setup + verification
# ═══════════════════════════════════════════════════════════════════════════════
step10_keycloak_and_verify() {
    log ""
    log "============================================"
    log "=== STEP 10: Keycloak Setup + Verify ==="
    log "============================================"

    load_creds

    # --- Keycloak realm setup ---
    if [ -f "$KEYCLOAK_SCRIPT" ]; then
        log "Running Keycloak setup: $KEYCLOAK_SCRIPT"
        bash "$KEYCLOAK_SCRIPT"
        log "Keycloak configuration complete"
    else
        die "Keycloak setup script not found: $KEYCLOAK_SCRIPT"
    fi

    # --- Verification ---
    log ""
    log "=== Verification ==="
    local errors=0

    # Check all pods
    log "Checking infra pods..."
    local not_ready
    not_ready=$(kubectl get pods -n azul-infra --no-headers 2>/dev/null \
        | grep -v "Completed" \
        | grep -cvE "([0-9]+)/\1\s+Running" 2>/dev/null) || not_ready="0"
    if [ "$not_ready" != "0" ]; then
        log "WARNING: $not_ready pods not ready in azul-infra"
        kubectl get pods -n azul-infra --no-headers | grep -v "Running\|Completed" || true
        errors=$((errors + 1))
    else
        log "  All infra pods: RUNNING"
    fi

    # Check Keycloak endpoint
    log "Checking Keycloak azul realm..."
    local kc_code
    kc_code=$(curl -k -sf -o /dev/null -w '%{http_code}' \
        -H "Host: ${KEYCLOAK_HOST}" https://${CLUSTER_IP}/realms/azul 2>/dev/null || echo "000")
    if [ "$kc_code" = "200" ]; then
        log "  Keycloak azul realm: OK ($kc_code)"
    else
        log "  WARNING: Keycloak azul realm returned $kc_code"
        errors=$((errors + 1))
    fi

    # Check OpenSearch cluster health
    log "Checking OpenSearch health..."
    local os_health
    os_health=$(kubectl exec azul-opensearch-nodes-0 -n azul-infra -- \
        curl -sf -u "admin:${OS_ADMIN_PASS}" -k https://localhost:9200/_cluster/health 2>/dev/null \
        | python3 -c "import sys,json; print(json.load(sys.stdin).get('status','unknown'))" 2>/dev/null || echo "unknown")
    if [ "$os_health" = "green" ] || [ "$os_health" = "yellow" ]; then
        log "  OpenSearch health: $os_health"
    else
        log "  WARNING: OpenSearch health: $os_health"
        errors=$((errors + 1))
    fi

    # Final status
    log ""
    if [ "$errors" -eq 0 ]; then
        log "=== INFRASTRUCTURE INSTALL COMPLETE — ALL CHECKS PASSED ==="
        send_discord "Infra Install" "success" "All infra pods running, Keycloak configured, OpenSearch healthy"
    else
        log "=== INFRASTRUCTURE INSTALL COMPLETE — $errors WARNING(S) ==="
        log "Check the warnings above. OpenSearch Dashboards may need a restart"
        log "after Keycloak is fully configured:"
        log "  kubectl rollout restart deployment azul-opensearch-dashboards -n azul-infra"
        send_discord "Infra Install" "success" "Install complete with $errors warning(s)"
    fi

    log ""
    log "Pod status:"
    kubectl get pods -n azul-infra -o wide 2>/dev/null || true
}

# ═══════════════════════════════════════════════════════════════════════════════
# CHECK — just show current state
# ═══════════════════════════════════════════════════════════════════════════════
cmd_check() {
    log "=== Current Infrastructure State ==="
    log ""
    log "Namespaces:"
    for ns in kafka opensearch-operator azul-infra; do
        if kubectl get namespace "$ns" >/dev/null 2>&1; then
            local count
            count=$(kubectl get pods -n "$ns" --no-headers 2>/dev/null | wc -l)
            log "  $ns: EXISTS ($count pods)"
        else
            log "  $ns: NOT FOUND"
        fi
    done

    log ""
    log "Helm releases:"
    for rel_ns in "strimzi-kafka-operator:kafka" "opensearch-operator:opensearch-operator" "azul-infra:azul-infra"; do
        local rel="${rel_ns%%:*}" ns="${rel_ns##*:}"
        if helm status "$rel" -n "$ns" >/dev/null 2>&1; then
            local rev
            rev=$(helm status "$rel" -n "$ns" -o json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('version','?'))" 2>/dev/null || echo "?")
            log "  $rel ($ns): INSTALLED (revision $rev)"
        else
            log "  $rel ($ns): NOT INSTALLED"
        fi
    done

    log ""
    log "Pods in azul-infra:"
    kubectl get pods -n azul-infra -o wide 2>/dev/null || log "  (namespace not found)"

    log ""
    log "Secrets in azul-infra:"
    kubectl get secrets -n azul-infra --no-headers 2>/dev/null | while read -r line; do log "  $line"; done

    log ""
    log "Certificates:"
    kubectl get certificates -n azul-infra 2>/dev/null || log "  (none)"
}

# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════
START_STEP=1
ACTION="install"

while [ $# -gt 0 ]; do
    case "$1" in
        --step)
            START_STEP="$2"
            shift 2
            ;;
        --check)
            ACTION="check"
            shift
            ;;
        --creds)
            ACTION="creds"
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  (none)        Full install (steps 1-10)"
            echo "  --step N      Start from step N (1-10)"
            echo "  --check       Show current state only"
            echo "  --creds       Generate credentials file only"
            echo ""
            echo "Steps:"
            echo "   1  Generate credentials       (.azul-credentials)"
            echo "   2  Install Strimzi operator    (kafka namespace)"
            echo "   3  Install OpenSearch operator  (opensearch-operator namespace)"
            echo "   4  Create namespace + secrets   (azul-infra namespace)"
            echo "   5  Helm install azul-infra      (all infra components)"
            echo "   6  Patch CA + wait for pods     (cert-manager → chart bundle)"
            echo "   7  OpenSearch unsafe-bootstrap   (single-node fix)"
            echo "   8  CoreDNS + Keycloak TLS cert  (DNS + certificate)"
            echo "   9  Bake CA into OpenSearch       (helm upgrade + restart)"
            echo "  10  Keycloak setup + verify       (realm, users, health checks)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1 (try --help)"
            exit 1
            ;;
    esac
done

case "$ACTION" in
    check)
        cmd_check
        exit 0
        ;;
    creds)
        step1_credentials
        exit 0
        ;;
    install)
        preflight

        [ "$START_STEP" -le 1 ]  && step1_credentials
        [ "$START_STEP" -le 2 ]  && step2_strimzi
        [ "$START_STEP" -le 3 ]  && step3_opensearch_operator
        [ "$START_STEP" -le 4 ]  && step4_namespace_secrets
        [ "$START_STEP" -le 5 ]  && step5_helm_install
        [ "$START_STEP" -le 6 ]  && step6_ca_and_wait
        [ "$START_STEP" -le 7 ]  && step7_opensearch_bootstrap
        [ "$START_STEP" -le 8 ]  && step8_coredns_and_keycloak_cert
        [ "$START_STEP" -le 9 ]  && step9_bake_ca
        [ "$START_STEP" -le 10 ] && step10_keycloak_and_verify
        ;;
esac
