#!/usr/bin/env bash
# AZUL Certificate Setup Script
# Generates and configures all TLS certificates required by the AZUL platform.
#
# This script handles:
#   1. Patching the self-signed CA into the chart's ca-certificates bundle
#      (so helm upgrade azul-infra preserves it permanently)
#   2. Creating the Keycloak TLS certificate (keycloak-tls)
#   3. Creating the Azul web UI TLS certificate (azul-web-tls)
#   4. Creating the CA configmap in the azul namespace (azul-ca-cert)
#
# The CA is generated by cert-manager during `helm install azul-infra`.
# This script must run AFTER the infra chart is installed.
#
# Usage:
#   ./setup-certs.sh all           # Run all certificate setup steps
#   ./setup-certs.sh patch-ca      # Only patch CA into chart bundle
#   ./setup-certs.sh keycloak      # Only create Keycloak TLS cert
#   ./setup-certs.sh azul          # Only create azul namespace certs
#
# Can also be sourced by other scripts:
#   source /data/AZUL/scripts/setup-certs.sh
#   patch_ca_into_chart
#
# Compatible with: Ubuntu 22.04+, RHEL 9+

# Only set options if running standalone (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -euo pipefail
fi

# Source central config if not already loaded
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -z "${AZUL_DIR:-}" ]; then
    source "${SCRIPT_DIR}/../azul.conf"
fi
INFRA_CHART="${INFRA_CHART:-${AZUL_DIR}/azul-app/infra}"
INFRA_VALUES="${INFRA_VALUES:-${AZUL_DIR}/azul-infra-values.yaml}"
CA_BUNDLE_FILE="${INFRA_CHART}/ca-certificates"

# Use the parent script's log function if available, otherwise define our own
if ! declare -f log >/dev/null 2>&1; then
    log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
fi

# --- Certificate Functions ---

# Extract the CA certificate PEM from the cluster secret
extract_ca_pem() {
    kubectl get secret azul-opensearch-ca-cert -n azul-infra \
        -o "jsonpath={.data.tls\.crt}" | base64 -d
}

# Wait for the CA certificate to be issued by cert-manager
wait_for_ca() {
    log "Waiting for cert-manager CA certificate..."
    local attempts=0
    while [ $attempts -lt 30 ]; do
        if kubectl get secret azul-opensearch-ca-cert -n azul-infra >/dev/null 2>&1; then
            log "CA certificate is ready"
            return 0
        fi
        sleep 5
        attempts=$((attempts + 1))
    done
    log "ERROR: CA certificate not found after 150s"
    return 1
}

# Patch the Test CA into the chart's ca-certificates bundle file on disk.
# After this, every helm install/upgrade azul-infra will include the Test CA
# in the opensearch-certs configmap natively — no post-install patching needed.
patch_ca_into_chart() {
    if [ ! -f "$CA_BUNDLE_FILE" ]; then
        log "ERROR: Chart CA bundle not found: $CA_BUNDLE_FILE"
        return 1
    fi

    # Check if already patched
    if grep -q "Homelab Test CA" "$CA_BUNDLE_FILE"; then
        log "Test CA already in chart CA bundle"
        return 0
    fi

    log "Extracting CA from cluster and patching into chart bundle..."
    local ca_pem
    ca_pem=$(extract_ca_pem)

    if [ -z "$ca_pem" ]; then
        log "ERROR: Failed to extract CA certificate from cluster"
        return 1
    fi

    # Append to the chart's ca-certificates file
    {
        echo ""
        echo "# Homelab Test CA (signs Keycloak TLS cert)"
        echo "# Added by setup-certs.sh — do NOT remove"
        echo "# If you git pull azul-app, re-run: ./scripts/setup-certs.sh patch-ca"
        echo "$ca_pem"
    } >> "$CA_BUNDLE_FILE"

    log "Test CA appended to chart bundle: $CA_BUNDLE_FILE"
}

# Create the Keycloak TLS certificate (signed by the CA issuer)
create_keycloak_cert() {
    if kubectl get certificate keycloak-tls -n azul-infra >/dev/null 2>&1; then
        log "Keycloak TLS certificate already exists"
        return 0
    fi

    cat <<'EOF' | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: azul-infra
spec:
  secretName: keycloak-tls
  issuerRef:
    name: azul-opensearch-ca-issuer
    kind: Issuer
  dnsNames:
    - ${KEYCLOAK_HOST}
  duration: 8760h
  renewBefore: 720h
EOF

    log "Keycloak TLS certificate created, waiting for issuance..."
    sleep 10
    kubectl wait --for=condition=Ready certificate/keycloak-tls -n azul-infra --timeout=60s 2>/dev/null || true
}

# Create azul namespace certificates:
# - Copy CA secret from azul-infra → azul
# - Create CA Issuer in azul namespace
# - Create azul-web-tls Certificate
create_azul_web_cert() {
    if kubectl get secret azul-web-tls -n azul >/dev/null 2>&1; then
        log "Secret azul-web-tls already exists"
        return 0
    fi

    log "Creating web TLS certificate..."

    # Copy CA secret to azul namespace (issuer is namespace-scoped)
    if ! kubectl get secret azul-opensearch-ca-cert -n azul >/dev/null 2>&1; then
        kubectl get secret azul-opensearch-ca-cert -n azul-infra -o json \
            | python3 -c "
import sys, json
s = json.load(sys.stdin)
s['metadata'] = {'name': 'azul-opensearch-ca-cert', 'namespace': 'azul'}
print(json.dumps(s))
" | kubectl apply -f -
    fi

    # Create Issuer
    if ! kubectl get issuer azul-ca-issuer -n azul >/dev/null 2>&1; then
        cat <<'EOISSUER' | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: azul-ca-issuer
  namespace: azul
spec:
  ca:
    secretName: azul-opensearch-ca-cert
EOISSUER
    fi

    # Create Certificate
    cat <<'EOCERT' | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: azul-web-tls
  namespace: azul
spec:
  secretName: azul-web-tls
  issuerRef:
    name: azul-ca-issuer
    kind: Issuer
  dnsNames:
    - ${AZUL_HOST}
  duration: 8760h
  renewBefore: 720h
EOCERT
    sleep 5
    kubectl wait --for=condition=Ready certificate/azul-web-tls -n azul --timeout=30s 2>/dev/null || true
    log "Created web TLS certificate: azul-web-tls"
}

# Create azul-ca-cert configmap in azul namespace (pods that need to trust the CA)
create_ca_configmap() {
    if kubectl get configmap azul-ca-cert -n azul >/dev/null 2>&1; then
        log "Configmap azul-ca-cert already exists"
        return 0
    fi

    log "Creating azul-ca-cert configmap from cluster secret..."
    local tmpfile="/tmp/ca-cert-$$.pem"
    kubectl get secret azul-opensearch-ca-cert -n azul-infra \
        -o jsonpath='{.data.ca\.crt}' | base64 -d > "$tmpfile"
    kubectl create configmap azul-ca-cert -n azul --from-file=ca.crt="$tmpfile"
    rm -f "$tmpfile"
    log "Created configmap: azul-ca-cert"
}

# --- Standalone Main ---

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    ACTION="${1:-all}"

    case "$ACTION" in
        patch-ca)
            wait_for_ca
            patch_ca_into_chart
            ;;
        keycloak)
            create_keycloak_cert
            ;;
        azul)
            kubectl create namespace azul 2>/dev/null || true
            create_azul_web_cert
            create_ca_configmap
            ;;
        all)
            log "=== AZUL Certificate Setup ==="
            log ""

            # 1. Wait for CA
            wait_for_ca

            # 2. Patch CA into chart bundle
            log "--- Step 1: Patching CA into chart bundle ---"
            patch_ca_into_chart

            # 3. Helm upgrade to apply patched bundle
            log ""
            log "--- Step 2: Applying patched bundle via helm upgrade ---"
            if helm status azul-infra -n azul-infra >/dev/null 2>&1; then
                helm upgrade azul-infra "$INFRA_CHART" -n azul-infra -f "$INFRA_VALUES" --timeout 5m
                log "azul-infra upgraded with Test CA in bundle"
            else
                log "WARNING: azul-infra not installed (CA will be included on first install)"
            fi

            # 4. Create Keycloak cert
            log ""
            log "--- Step 3: Creating Keycloak TLS certificate ---"
            create_keycloak_cert

            # 5. Create azul namespace certs (if namespace exists)
            if kubectl get namespace azul >/dev/null 2>&1; then
                log ""
                log "--- Step 4: Creating azul namespace certificates ---"
                create_azul_web_cert
                create_ca_configmap
            else
                log ""
                log "--- Step 4: Skipped (azul namespace doesn't exist yet) ---"
            fi

            log ""
            log "=== Certificate Setup Complete ==="
            ;;
        *)
            echo "Usage: $0 {all|patch-ca|keycloak|azul}"
            echo ""
            echo "Commands:"
            echo "  all       - Full certificate setup (default)"
            echo "  patch-ca  - Only patch CA into chart CA bundle"
            echo "  keycloak  - Only create Keycloak TLS certificate"
            echo "  azul      - Only create azul namespace certs"
            echo ""
            echo "Can also be sourced: source $0"
            exit 1
            ;;
    esac
fi
